### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wyatt-wong** [milliluk/LWTools#1]
I cloned the GitHub source and build it under macOS and I got linking error below. How to resolve it ?

```
wyattwong@MacBookPro LWTools % make
Linking lwasm/lwasm
Undefined symbols for architecture x86_64:
  "_do_audit", referenced from:
      _main in main.o
  "_do_cmt", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:129: lwasm/lwasm] Error 1
wyattwong@MacBookPro LWTools % 
```

**Comment by milliluk** [comment]
The build uses CMake. From the root of the project:

```
mkdir build
cd build
cmake ..
make
```

This is an old fork with some experimental changes. Most were picked up by the main branch. You may prefer:
```
brew install lwtools
```

Or pick up more recent source:
http://www.lwtools.ca/

**Comment by wyatt-wong** [comment]
> The build uses CMake. From the root of the project:
> 
> ```
> mkdir build
> cd build
> cmake ..
> make
> ```
> 
> This is an old fork with some experimental changes. Most were picked up by the main branch. You may prefer:
> 
> ```
> brew install lwtools
> ```
> 
> Or pick up more recent source: http://www.lwtools.ca/

In that case, the README.md file should be revised ?

**Comment by milliluk** [comment]
Updated the Makefile. Either option should work now.

**Comment by wyatt-wong** [comment]
I noticed the lwtools-4.19.tar.gz from http://www.lwtools.ca/ is newer. The lwasm version from lwtools-4.19.tar.gz is 4.19 whereas the lwasm version build from this GitHub source is 4.17+

**Comment by milliluk** [comment]
Yes, that link is on the landing page which also states that this is a development fork. That's GitHub parlance for "work I'm choosing to share in case it's useful in some fringe case."

You're probably in the wrong place.

For binaries, install [Homebrew](https://brew.sh/) then:
```
brew install lwtools
```

Or pull the version you want from the main project and build from source.

**Comment by wyatt-wong** [comment]
I wasn't paying attention that this GitHub page is a "development fork". In fact I found your page [http://www.lwtools.ca/](url) first while I was checking the [https://github.com/n6il/toolshed](url) page before I found this GitHub page.

I have installed Homebrew shortly after I procured my Mac 10 years ago. Initially I used brew to install different tools but I found that building from the source is better as I can always get the latest version. And in my view most people put the latest source in GitHub page instead of putting the source in their homepage. With GitHub I can always retrieve the latest version with "git pull" command. If I downloaded the source from the homepage, I have to regularly keep track of the update of the homepage as well as re-download the  latest source file of xxxx.tar.gz

**Comment by milliluk** [comment]
I am not the original author of LWTools. And that's not my website. 

Building from source is noble however in this case you landed on an old version, couldn't build it despite it having CI builds lit up green, a .travis.yml file documenting all dependencies and build steps, plus a CMakeLists.txt file shining a flashlight at using CMake, You were about to run code from a person you do not know.

brew has the current version. Just use it.

**Comment by wyatt-wong** [comment]
As you said so, I found the "wrong" page but at least I discovered something wrong in the Makefile and caused your attention to fix it. And I don't see anything wrong building a tool from the source, this is the GOLD Standard in my view.
